#!/bin/bash

################################################################################
# This script cleans the autogenerated files and folders from the scripts of   #
# the usda-database-generator project other than the database.                 #
################################################################################

# Variables
TMP_DATA_DIR="tmp"

# Check if we are in the usda-database-generator project
if [[ ${PWD##*/} == "usda-database-generator" ]]
then

    # Removing folders
    rm "$TMP_DATA_DIR" -rf

# Exiting if the current directory is not the project of the project
else
    echo "ERROR: Current directory is not usda-database-generator. Exiting."
fi