#!/bin/bash

################################################################################
# This script creates the database to be used and inserts the data in the CSV  #
# files provided by the USDA Data Central into the same database.              #
################################################################################

# Variables
TMP_DATA_DIR="tmp"
SCRIPTS_DIR="scripts"

# Check if we are in the usda-database-generator project
if [[ ${PWD##*/} == "usda-database-generator" ]]
then

    # Removing the database if there is an existing one
    if [[ -f "database.db" ]]
    then
        rm "database.db"
    fi

    python3 "$SCRIPTS_DIR"/create.py

    # Extracting CSV files
    ./"$SCRIPTS_DIR/extract.sh"

    # For all the CSV files in the directory
    for file in "$TMP_DATA_DIR/"*
    do
        python3 "$SCRIPTS_DIR"/insert.py "$file"
    done

    # Cleaning autogenerated files and folders
    ./"$SCRIPTS_DIR/clean.sh"

# Exiting if the current directory is not the project of the project
else
    echo "ERROR: Current directory is not usda-database-generator. Exiting."
fi